version: '3.8'

services:
  product:
    build:
      context: product
    container_name: product
    ports:
      - "8002:8002"
  
  order:
    build:
      context: order
    container_name: order
    ports:
      - "80001:8001"
  
  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - product
      - order